services:
  postgres:
    image: postgres:18-alpine
    container_name: biomechanics_postgres
    environment:
      POSTGRES_DB: biomechanics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      # - C:\Users\Andreea\Documents\backup_local.sql:/docker-entrypoint-initdb.d/backup_local.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biomechanics_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biomechanics_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PYTHON_SERVICE_URL: http://data-processing:5000
    depends_on:
      postgres:
        condition: service_healthy

  data-processing:
    build:
      context: ./data-processing
      dockerfile: Dockerfile
    container_name: biomechanics_python
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biomechanics_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: